import axios from 'axios'

export const FETCH_SMURFS = "FETCH_SMURFS"
export const FETCH_SMURFS_SUCCESS = "FETCH_SMURFS_SUCCESS"
export const FETCH_SMURFS_FAIL = "FETCH_SMURFS_FAIL"
export const ADD_SMURFS = "ADD_SMURFS"
export const ADD_SMURFS_SUCCESS = "ADD_SMURFS_SUCCESS"
export const ADD_SMURFS_FAIL = "ADD_SMURFS_FAIL"